# Generated by Django 5.2.7 on 2025-10-16 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='author',
            new_name='user',
        ),
    ]
